### ISSUE TITLE
老哥 ，脚本有不有使用的demo呢 直接报更新版本号失败了

### ISSUE THREAD

**Issue by NickTet** [moonljt521/flutter#2]
老哥 ，脚本有不有使用的demo呢 直接报更新版本号失败了

**Comment by moonljt521** [comment]
@NickTet   里边的核心流程是打包，编译产物； 大部分脚本内容是根据我本地环境定制的，你看下shell的代码，把不匹配的修改下或者直接注释掉： 比如更新版本号的，我是在module根目录下的结构   root/bak/gradle.properties      里添加了版本

upSnapshot=false
sonatypePackaging=aar
sonatypeGroupId=xxx.xxxx
sonatypeArtifactId=xxx
sonatypeVersion=1.0.0.1

目的是每次让版本自动加1，不需要你手动改就行。

我贴出这个脚本的主要目的是展示如何生成中间产物和assets资源，其他的都是根据本地环境定制修改下。。。

回头我再写个帖子吧，把脚本详细说明一下。。。。

**Comment by moonljt521** [comment]
https://github.com/moonljt521/flutter_module_package/blob/master/flutter.sh
新建了个仓库，项目相关的目录是匹配脚本的，参考下

**Comment by NickTet** [comment]
好 谢了
